# Generated by Django 4.1.4 on 2023-01-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cat_use',
            field=models.CharField(default=1, max_length=30, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            preserve_default=False,
        ),
    ]
